### ISSUE TITLE
ftdetect takes significant time on startup

### ISSUE THREAD

**Issue by fourjay** [fladson/vim-kitty#14]
I try to keep my vim startup time low, and notice that the ftdetect processing time pushes vim-kitty up to the top of my load time.
Looking at it, I think directory matching pattern covers the XDG_CONFIG_HOME matching (which I also causes the load). Basically, wherever the XDG home is */kitty/ should match the kitty config files.
The change is simple, I made a fork with branch here:
https://github.com/fourjay/vim-kitty/tree/ftdetect
With it, the ftdetect seems to work fine, and startup time goes down to almost nothing

**Comment by fladson** [comment]
Thanks @fourjay for reporting and fixing it!

**Comment by pdf** [comment]
After this change, detection no longer works for me, editing any `~/.config/kitty/*.conf` file.

**Comment by fladson** [comment]
Thanks for the note @pdf, I just merged a new change that should fix that.
