### ISSUE TITLE
Enhancement: Highlight keywords when they are not at the start of the line

### ISSUE THREAD

**Issue by dimitris-k** [fladson/vim-kitty#18]
Configuration keywords are only highlighted when they appear at the first character of the lines of the config file.  Sometimes I use to indent some config directives for grouping purposes, e.g. when testing some feature. It would be nice then, to have these keywords highlighted... Please, see the attached screenshot.

![kitty2](https://user-images.githubusercontent.com/8190406/153853502-78d91ebd-5653-4d56-a893-cf9dd8e79ac2.png)

**Comment by fladson** [comment]
Good point @dimitris-k
I will flag this as a nice `first-issue` so anyone interested in contributing can feel free to grab it.
I will try to take a look at it this weekend.

**Comment by dimitris-k** [comment]
Hi @fladson and contributors.

I did some reading on how to write a vim syntax file. The issue **can be resolved** by slightly modifying the `kittyKW`, `kittyMap` and `kittyInclude` syntax matching rules, as follows:
```
syn match kittyKW '^\s*\S*' contains=kittyKeyword,kittyInvalidKeyword nextgroup=kittySt
syn match kittyInclude /^\s*include/ display
syn match kittyMap '^\s*\(mouse_\)\?map' nextgroup=kittyKeybind
```
You can easily see, that I added `\s*` to match optional white space after the start of line... 😀 

I hope you review and test this suggested solution and if you feel happy το incorporate it in [kitty.vim](https://github.com/fladson/vim-kitty/blob/main/syntax/kitty.vim).

**Comment by fladson** [comment]
Thanks @dimitris-k I did some initial testing with those changes and it's looking good.

**Comment by fladson** [comment]
Do you want to open a PR with the changes or can I do it?

**Comment by dimitris-k** [comment]
Please, do it... Thanks!
