### ISSUE TITLE
Unable to load vim-kitty

### ISSUE THREAD

**Issue by Strykar** [fladson/vim-kitty#24]
If I try to `:set ft-kitty` I get:
```
filetype=conf
E488: Trailing characters: ft-kitty
Press ENTER or type command to continue
```
How do I troubleshoot this?
Running `vim 9.0.0814` on Arch linux.

**Comment by fladson** [comment]
Did you try `:set ft=kitty`?

**Comment by Strykar** [comment]
Voops, I have tried that too and it doesn't post an error but no hightlighting either.
I did have `# vim:ft=kitty` set inside kitty.conf and that's what led me to believe it wasn't working,

**Comment by fladson** [comment]
I did some debugging with vim and looks like the installation steps are a bit off. Try this instead and see if it works:

```
git clone https://github.com/fladson/vim-kitty.git /tmp/vim-kitty
mkdir -p ~/.vim/after/syntax/
mv /tmp/vim-kitty/syntax/* ~/.vim/after/syntax/
rm -rf /tmp/vim-kitty
```

**Comment by Strykar** [comment]
That was the issue, fixed! Thank you.

**Comment by Strykar** [comment]
Reopening this as it does not appear to be fixed, sorry only noticed it this morning.
Now `:set ft=kitty` does not throw an error but the syntax highlights, which had appeared once, do not show.

**Comment by Strykar** [comment]
@fladson Anything else I can try to help troubleshoot?

**Comment by pixelastic** [comment]
FWIW, I had issues installing it as well, because my vim plugin manager (`vim-plug`) would assume `master` as the default branch to pull it from, and not `main`.

Once I added `Plug 'fladson/vim-kitty', { 'branch': 'main' }` instead of `Plug 'fladson/vim-kitty'` in my `vimrc`, and ran `:PlugUpdate`, it detected the plugin correctly.

Hope that helps

**Comment by fladson** [comment]
@Strykar let me know if you are still facing issues here.
