### ISSUE TITLE
mouse_map: click, release, press, etc.

### ISSUE THREAD

**Issue by wookayin** [fladson/vim-kitty#25]
https://sw.kovidgoyal.net/kitty/conf/#mouse-actions

Mouse actions like `click`, `press`, `release`, `doublepress`, `triplepress`, etc. are not highlighted. It would be great to add a support for these new syntax keywords.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/1009873/206034587-712a2a3f-cb16-456a-8236-cd1b5de0d9ec.png">

**Comment by fladson** [comment]
Done at 11ed0c3f97596e402c9aef226535e2fefd65f3d7
