### ISSUE TITLE
Mark kittyKeyword as not a region to spellcheck

### ISSUE THREAD

**Issue by nogweii** [fladson/vim-kitty#28]
Right now things like `color0`...`color15` get highlighted in my editor as spelling mistakes. 😆 

    syntax match kittyKeyword ... contains=@NoSpell

Is the basic syntax, though I'm not sure how you'd want to integrate it into the code generation.

**Comment by fladson** [comment]
@nogweii I couldn't replicate it, this is very dependant on your nvim config.
Feel free to send a contribution to fix it for your case and we can check if it doesn't break anything else.
